AWSTemplateFormatVersion: 2010-09-09
Description: Ecomm Infrastructure
Resources:
 # VPC
 ecommVPC:
   Type: AWS::EC2::VPC
   Properties:
     CidrBlock: 10.0.0.0/16
     EnableDnsSupport: 'true'
     EnableDnsHostnames: 'true'
     Tags:
       - Key: Name
         Value: ecomm-vpc
 # Web Subnet         
 ecommwebSubnet:
   Type: AWS::EC2::Subnet
   Properties:
     VpcId: !Ref ecommVPC
     CidrBlock: 10.0.0.0/24
     AvailabilityZone: "eu-west-2a"
     MapPublicIpOnLaunch: "true"
     Tags:
     - Key: Name
       Value: ecomm-web-subnet
