AWSTemplateFormatVersion: 2010-09-09
Description: Ecomm Infrastructure
Resources:
 # VPC
 ecommVPC:
   Type: AWS::EC2::VPC
   Properties:
     CidrBlock: 10.0.0.0/16
     EnableDnsSupport: 'true'
     EnableDnsHostnames: 'true'
     Tags:
       - Key: Name
         Value: ecomm-vpc
 # Web Subnet         
 ecommwebSubnet:
   Type: AWS::EC2::Subnet
   Properties:
     VpcId: !Ref ecommVPC
     CidrBlock: 10.0.0.0/24
     AvailabilityZone: "eu-west-2a"
     MapPublicIpOnLaunch: "true"
     Tags:
     - Key: Name
       Value: ecomm-web-subnet
  # App Subnet         
 ecommappSubnet:
   Type: AWS::EC2::Subnet
   Properties:
     VpcId: !Ref ecommVPC
     CidrBlock: 10.0.1.0/24
     AvailabilityZone: "eu-west-2a"
     MapPublicIpOnLaunch: "true"
     Tags:
     - Key: Name
       Value: ecomm-app-subnet
 # DB Subnet         
 ecommdbSubnet:
   Type: AWS::EC2::Subnet
   Properties:
     VpcId: !Ref ecommVPC
     CidrBlock: 10.0.2.0/24
     AvailabilityZone: "eu-west-2a"
     MapPublicIpOnLaunch: "false"
     Tags:
     - Key: Name
       Value: ecomm-db-subnet
 # Internet Gateway
 ecommInternetGateway:
   Type: AWS::EC2::InternetGateway
   Properties:
     Tags:
     - Key: Name
       Value: ecomm-igw
  # Attach Internet Gateway     
 ecommAttachGateway:
   Type: AWS::EC2::VPCGatewayAttachment
   Properties:
     VpcId:
       Ref: ecommVPC
     InternetGatewayId:
       Ref: ecommInternetGateway
  # Public Route Table
 ecommpubRouteTable:
   Type: AWS::EC2::RouteTable
   Properties:
     VpcId: 
       Ref: ecommVPC
     Tags:
     - Key: Name
       Value: ecomm-pub-rt
  # Internet Route
 myRoute:
   Type: AWS::EC2::Route
   DependsOn: ecommAttachGateway
   Properties:
      RouteTableId:
        Ref: ecommpubRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: ecommInternetGateway
  
 # RT - Subnet Association
 ecommwebSubnetRouteTableAssociation:
   Type: AWS::EC2::SubnetRouteTableAssociation
   Properties:
     SubnetId:
       Ref: ecommwebSubnet
     RouteTableId:
       Ref: ecommpubRouteTable


 # RT - Subnet Association
 ecommappSubnetRouteTableAssociation:
   Type: AWS::EC2::SubnetRouteTableAssociation
   Properties:
     SubnetId:
       Ref: ecommappSubnet
     RouteTableId:
       Ref: ecommpubRouteTable
  # Private Route Table
 ecommpvtRouteTable:
   Type: AWS::EC2::RouteTable
   Properties:
     VpcId: 
       Ref: ecommVPC
     Tags:
     - Key: Name
       Value: ecomm-pvt-rt


 # RT - Subnet Association
 ecommdbSubnetRouteTableAssociation:
   Type: AWS::EC2::SubnetRouteTableAssociation
   Properties:
     SubnetId:
       Ref: ecommdbSubnet
     RouteTableId:
       Ref: ecommpvtRouteTable
  # RT - Subnet Association
 ecommwebNetworkAcl:
   Type: AWS::EC2::NetworkAcl
   Properties:
     VpcId:
       Ref: ecommVPC
     Tags:
       - Key: Name
         Value: ecomm-web-nacl
 # Web NACL Rules
 ecommwebnaclInboundRule:
   Type: AWS::EC2::NetworkAclEntry
   Properties:
      NetworkAclId:
        Ref: ecommwebNetworkAcl
      RuleNumber: 100
      Protocol: 6
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 0
        To: 65535
 ecommwebnaclOutboundRule:
   Type: AWS::EC2::NetworkAclEntry
   Properties:
      NetworkAclId:
        Ref: ecommwebNetworkAcl
      RuleNumber: 100
      Protocol: -1
      Egress: true
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
  # Web NACL Association      
 ecommwebSubnetNetworkAclAssociation:
   Type: AWS::EC2::SubnetNetworkAclAssociation
   Properties:
     SubnetId:
       Ref: ecommwebSubnet
     NetworkAclId:
       Ref: ecommwebNetworkAcl


# App NACL
 ecommappNetworkAcl:
   Type: AWS::EC2::NetworkAcl
   Properties:
     VpcId:
       Ref: ecommVPC
     Tags:
       - Key: Name
         Value: ecomm-app-nacl
 # App NACL Rules
 ecommappnaclInboundRule:
   Type: AWS::EC2::NetworkAclEntry
   Properties:
     NetworkAclId:
       Ref: ecommappNetworkAcl
     RuleNumber: 100
     Protocol: 6
     RuleAction: allow
     CidrBlock: 0.0.0.0/0
     PortRange:
       From: 0
       To: 65535
 ecommappnaclOutboundRule:
   Type: AWS::EC2::NetworkAclEntry
   Properties:
     NetworkAclId:
       Ref: ecommappNetworkAcl
     RuleNumber: 100
     Protocol: -1
     Egress: true
     RuleAction: allow
     CidrBlock: 0.0.0.0/0


# App NACL Association      
 ecommappSubnetNetworkAclAssociation:
   Type: AWS::EC2::SubnetNetworkAclAssociation
   Properties:
     SubnetId:
       Ref: ecommappSubnet
     NetworkAclId:
       Ref: ecommappNetworkAcl




# DB NACL
 ecommdbNetworkAcl:
   Type: AWS::EC2::NetworkAcl
   Properties:
     VpcId:
       Ref: ecommVPC
     Tags:
       - Key: Name
         Value: ecomm-db-nacl
 # DB NACL Rules
 ecommdbnaclInboundRule:
   Type: AWS::EC2::NetworkAclEntry
   Properties:
     NetworkAclId:
       Ref: ecommdbNetworkAcl
     RuleNumber: 100
     Protocol: 6
     RuleAction: allow
     CidrBlock: 0.0.0.0/0
     PortRange:
       From: 0
       To: 65535
 ecommdbnaclOutboundRule:
   Type: AWS::EC2::NetworkAclEntry
   Properties:
     NetworkAclId:
       Ref: ecommdbNetworkAcl
     RuleNumber: 100
     Protocol: -1
     Egress: true
     RuleAction: allow
     CidrBlock: 0.0.0.0/0
  # DB NACL Association      
 ecommdbSubnetNetworkAclAssociation:
   Type: AWS::EC2::SubnetNetworkAclAssociation
   Properties:
     SubnetId:
       Ref: ecommdbSubnet
     NetworkAclId:
       Ref: ecommdbNetworkAcl


# Web Secuirty Group
 ecommwebInstanceSecurityGroup:
   Type: AWS::EC2::SecurityGroup
   Properties:
     GroupDescription: Allow ssh & http to client host
     VpcId: !Ref ecommVPC
     SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: 22
         ToPort: 22
         CidrIp: 0.0.0.0/0
       - IpProtocol: tcp
         FromPort: 80
         ToPort: 80
         CidrIp: 0.0.0.0/0 
     SecurityGroupEgress:
       - IpProtocol: tcp
         FromPort: 0
         ToPort: 65535
         CidrIp: 0.0.0.0/0
     Tags:
       - Key: Name
         Value: ecomm-web-sg


# App Secuirty Group
 ecommappInstanceSecurityGroup:
   Type: AWS::EC2::SecurityGroup
   Properties:
     GroupDescription: Allow ssh & http to client host
     VpcId: !Ref ecommVPC
     SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: 22
         ToPort: 22
         CidrIp: 0.0.0.0/0
       - IpProtocol: tcp
         FromPort: 3000
         ToPort: 3000
         CidrIp: 0.0.0.0/0 
     SecurityGroupEgress:
       - IpProtocol: tcp
         FromPort: 0
         ToPort: 65535
         CidrIp: 0.0.0.0/0
     Tags:
       - Key: Name
         Value: ecomm-app-sg


# DB Secuirty Group
 ecommdbInstanceSecurityGroup:
   Type: AWS::EC2::SecurityGroup
   Properties:
     GroupDescription: Allow ssh & mysql to client host
     VpcId: !Ref ecommVPC
     SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: 22
         ToPort: 22
         CidrIp: 0.0.0.0/0
       - IpProtocol: tcp
         FromPort: 3306
         ToPort: 3306
         CidrIp: 0.0.0.0/0 
     SecurityGroupEgress:
       - IpProtocol: tcp
         FromPort: 0
         ToPort: 65535
         CidrIp: 0.0.0.0/0
     Tags:
       - Key: Name
         Value: ecomm-db-sg
  # Web Instance
 ecommwebInstance:
   Type: 'AWS::EC2::Instance'
   Properties:
     ImageId: ami-0fbbcfb8985f9a341
     InstanceType: t2.micro
     KeyName: mykeypair
     SubnetId:
       Ref: ecommwebSubnet
     SecurityGroupIds:
       - Ref: ecommwebInstanceSecurityGroup
     UserData:
       Fn::Base64: !Sub |
         #!/bin/bash
         yum update -y
         yum install httpd git -y
         systemctl start httpd
         systemctl enable httpd
         git clone https://github.com/ravi2krishna/ecomm.git /var/www/html
     Tags:
       - Key: Name
         Value: ecomm-web-server 
